### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.uniform(0, 1, 10)

In [18]:
vector, vector.shape

(array([0.50469671, 0.55200104, 0.7919139 , 0.81606313, 0.3167075 ,
        0.27741341, 0.35768026, 0.48063261, 0.47029509, 0.33377765]),
 (10,))

In [4]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])

In [19]:
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [6]:
vector_plus_10 = vector + 10
np.round(vector_plus_10, 2)

array([10.5 , 10.55, 10.79, 10.82, 10.32, 10.28, 10.36, 10.48, 10.47,
       10.33])

In [7]:
matrix_mult_const = matrix * 2
matrix_mult_const

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [8]:
vector_2 = vector_plus_10 ** 2
vector_2

array([110.34865291, 111.3447259 , 116.46540565, 116.98722156,
       106.43445373, 105.62522635, 107.28154047, 109.84365994,
       109.62707935, 106.78696059])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [10]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Результатом буде вектор 2х1, що відповідає 2 рядку мартиці.

In [11]:
result_mult_C = np.dot(result_matrix, C)
result_mult_C

array([[0.5202],
       [0.2846]])

In [12]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [13]:
result_matrix_T = result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [14]:
vector_T = vector.T
vector_T

array([0.50469671, 0.55200104, 0.7919139 , 0.81606313, 0.3167075 ,
       0.27741341, 0.35768026, 0.48063261, 0.47029509, 0.33377765])

Структура вектора не змінилась. Це одновимірний вектор, що задає напрямок горизонтально, по рядку.

In [15]:
column_vector = np.expand_dims(vector, axis=1)

In [16]:
column_vector

array([[0.50469671],
       [0.55200104],
       [0.7919139 ],
       [0.81606313],
       [0.3167075 ],
       [0.27741341],
       [0.35768026],
       [0.48063261],
       [0.47029509],
       [0.33377765]])

In [17]:
column_vector.T
column_vector, column_vector.shape

(array([[0.50469671],
        [0.55200104],
        [0.7919139 ],
        [0.81606313],
        [0.3167075 ],
        [0.27741341],
        [0.35768026],
        [0.48063261],
        [0.47029509],
        [0.33377765]]),
 (10, 1))